markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "草根创业者 · 老王"
markdown: rdiscount

author: "laowang24"
atom-baseurl: "http://http://laowang24.github.io"
disqus: "echowlt"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://weibo.com/laowang24 
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
  - title: Subscribe
    class: fa fa-weibo 
    href: http://weibo.com/laowang24 

